events {
    worker_connections 1024;
}

http {
    upstream crypt_backend {
        ip_hash; 
        server crypt:7433;
    }
    
    server {
        listen 80;
        
        location / {
            proxy_pass http://crypt_backend;
        }
    }
}
